<main id="register_page" class="flex-column justify-center align-center">

    <h1>Inscription</h1>


    <form action="" method="POST" class="col-12 col-tablet-6 col-desktop-4 flex-column">

        <label for="username">
            Nom d'utilisateur
            <input id="username" name="username" type="text">
        </label>
        
        <label for="email">
            Email
            <input id="email" name="email" type="email">
        </label>
        
        
        <label for="password">Mot de passe
            <div class="password-wrapper">
                <input type="password" id="password" name="password" required>
                <i class="fa-regular fa-eye togglePassword"></i>
            </div>
        </label>
 
        <p>Votre mot de passe doit contenir entre 8 et 16 lettres, avec au moins une majuscule, une minuscule, 1 chiffre et 1 caractère spécial.</p>

        <button class="btn btn-primary" type="submit">S'inscrire</button>
        
        

   
        <?php if( isset( $error ) && !empty( $error ) ) : ?>
            <p class="txt-error">
                <?= htmlspecialchars($error) ?>
            </p>
        <?php endif ?>

    </form>

</main>